name: Super-Linker

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Super-Linker
      uses: github/super-linker@v4
      env:
       DEFAULT_BRANCH: main
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
